import type { Metadata } from "next";
import { Exo } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";
import {ClerkProvider} from "@clerk/nextjs"
import { dark } from "@clerk/themes"
import { ThemeProvider } from "./providers/ThemeProvider";

const exo = Exo({subsets: ["latin"]})



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider appearance={{baseTheme:dark}}>
      <html lang="en" suppressHydrationWarning>
        <body className={exo.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
